### ISSUE TITLE
Project is empty

### ISSUE THREAD

**Issue by Cutta** [arriolac/GitHubRxJava#2]
Project is not including rxjava using samples

**Comment by kosratdev** [comment]
Hi @Cutta 
the project source code in the **solution** branch.
@arriolac please change default branch from **master** to **solution** branch.

**Comment by Cutta** [comment]
Thank you @KosratDAhmad , I could see. But everyone cannot see the solution branch. If @arriolac will change default branch, I will close the issue.

**Comment by arriolac** [comment]
Merged `solution` to `master`.
